apiVersion: apps/v1
kind: Deployment
metadata:
  name: beach
spec:
  selector:
    matchLabels:
      run: beach
  replicas: 2
  template:
    metadata:
      labels:
        run: beach
    spec:
      containers:
       - name: beach
         image: jagluck/beach-site:latest
         ports:
          -  containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: beach
  labels:
    run: beach
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    run: beach